name: Bug Report
description: Create a bug report
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue:

        - Do a search of existing issues.
        - Pull and test the latest updates from this repository's `dev` branch.

  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, or a link to the reproducible repository.
      placeholder: |
        1. Run the `npm run hipsum` script
        2. Observe Hilichurlian sentence in the log output
        3. Nothing appears in the log
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: A clear and concise description of what the bug is, and what you expected to happen.
      placeholder: 'Following the steps from the previous section, I expected to see A, but I observed B instead'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Provide environment information
      description: Please run `npm run info` in the root directory of your project and paste the results.
      render: bash
      placeholder: |
        Node version: v20.15.0
        Platform: linux
        Arch: x64
        V8 version: 11.3.244.8-node.23
        npm version: 10.7.0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - 'Not sure'
        - 'Hilichurlian data dictionary'
        - '"npm run scrape" script'
        - '"npm run hipsum" script'
        - 'Tests'
        - 'Others'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate.
      placeholder: |
        I tested my reproduction against the latest hili-lipsum releases, and the first one that introduced the bug was "v3.2.1", since reverting to "v3.2.0" works.
